In [68]:
 # let's do some basics

In [99]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split


In [100]:
df = pd.read_csv(r"/home/sarthakredasani/Documents/CDAC_ML/Datasets/Datasets/Exp_Salaries.csv")

In [101]:
df.head(3)

Salary  Years_Previous_Experience  ...  Department  Number_Supervised
0   32782                          1  ...           A                  0
1   32920                          3  ...           A                  4
2   29548                          6  ...           A                  0

[3 rows x 7 columns]

In [72]:
# let's drop the unnessary col
# first will store it in another variable

In [102]:
train, test = train_test_split(df, test_size=0.3, random_state=50)

In [74]:
train.columns

Index(['Salary', 'Years_Previous_Experience', 'Years Employed',
       'Years_Education', 'Gender', 'Department', 'Number_Supervised'],
      dtype='object')

In [103]:
X_train = train.drop(['Gender', 'Department', 'Salary'], axis =1)
X_test = test.drop(['Gender', 'Department', 'Salary'], axis =1)
y_train = train['Salary']
y_test = test['Salary']
X_train.columns


Index(['Years_Previous_Experience', 'Years Employed', 'Years_Education',
       'Number_Supervised'],
      dtype='object')

In [76]:
X_test

Years_Previous_Experience  ...  Number_Supervised
14                          4  ...                  2
7                           4  ...                  9
41                          6  ...                  3
29                          2  ...                  2
17                          3  ...                  6
36                          4  ...                  0
38                          6  ...                  1
37                          5  ...                  5
19                          4  ...                  8
2                           6  ...                  0
21                          0  ...                  3
11                          5  ...                  5
6                          16  ...                  7
40                         19  ...                 40

[14 rows x 4 columns]

In [77]:
X_train.columns

Index(['Years_Previous_Experience', 'Years Employed', 'Years_Education',
       'Number_Supervised'],
      dtype='object')

In [78]:
#  using linear regression model

In [104]:
lr = LinearRegression()
lr.fit(X_train, y_train)


LinearRegression()

In [105]:
lr.coef_, lr.intercept_

(array([-272.24698509,  534.26519935, 2114.18493872,   79.14634625]),
 24851.43313248771)

In [106]:
# just checking the value 
v1 = 23598.113344434 + 5.06730251*1 + 729.64208918*0 + 1488.0137908*7 + 178.41380514*0
v1

34019.277182544

In [107]:
y_pred = lr.predict(X_test)
y_pred

array([51392.92000095, 34890.51094374, 60491.96153148, 38676.40905593,
       33352.51128728, 34221.83391013, 25009.72582499, 28797.32725399,
       36399.80979088, 44505.87121461, 38003.61038849, 32658.25007861,
       35583.0688356 , 43446.15626928])

In [108]:
y_test.values

array([32920, 34632, 69246, 39743, 28985, 43674, 23654, 26452, 36571,
       47536, 31425, 29876, 35631, 36578])

In [94]:
#  almost same value comming there is some error

In [109]:
# now let's find the error

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

print(mean_absolute_error(y_test, y_pred))
print(mean_squared_error(y_test, y_pred))
print(r2_score(y_test, y_pred))

4682.218407764956
45874817.33705418
0.6137400321316115


In [111]:
from sklearn.linear_model import Ridge

ridge = Ridge()
ridge.fit(X_train, y_train)
y_pred1 = ridge.predict(X_test)


print(mean_absolute_error(y_test, y_pred1))
print(mean_squared_error(y_test, y_pred1))
print(r2_score(y_test, y_pred1))


4678.260166366059
45699743.04914312
0.6152141347602118


In [112]:
from sklearn.linear_model import Lasso

lasso = Lasso()
lasso.fit(X_train, y_train)
y_pred1 = lasso.predict(X_test)
print(mean_absolute_error(y_test, y_pred1))
print(mean_squared_error(y_test, y_pred1))
print(r2_score(y_test, y_pred1))

4682.159373998243
45872895.0979277
0.6137562171338924
