In [1]:
# Polynomial Features

In [2]:
import pandas as pd
import numpy as np
from sklearn.linear_model import *
from sklearn.model_selection import *
from sklearn.metrics import *
from sklearn.preprocessing import *
import os

In [4]:
import sklearn
sklearn.__version__

'1.6.1'

In [5]:
df = pd.read_csv(r"/home/sarthakredasani/Documents/CDAC_ML/Datasets/Datasets/Housing.csv")
df.head(5)

price  lotsize  bedrooms  bathrms  ...  gashw airco garagepl prefarea
0  42000.0     5850         3        1  ...     no    no        1       no
1  38500.0     4000         2        1  ...     no    no        0       no
2  49500.0     3060         3        1  ...     no    no        0       no
3  60500.0     6650         3        1  ...     no    no        0       no
4  61000.0     6360         2        1  ...     no    no        0       no

[5 rows x 12 columns]

In [ ]:
# as we are focus on polynomial feature 
# see carefully what is X and y

In [7]:
dum_df= pd.get_dummies(df, drop_first=True)
X, y = dum_df[['lotsize']], dum_df['price']

In [8]:
dum_df.columns

Index(['price', 'lotsize', 'bedrooms', 'bathrms', 'stories', 'garagepl',
       'driveway_yes', 'recroom_yes', 'fullbase_yes', 'gashw_yes', 'airco_yes',
       'prefarea_yes'],
      dtype='object')

In [9]:
lr = LinearRegression()
lr.fit(X,y)
lr.coef_ , lr.intercept_

(array([6.59876759]), 34136.191564915054)

In [10]:
# Polynomial Transformation

In [11]:
poly = PolynomialFeatures(degree=2, include_bias=False).set_output(transform='pandas')
X_poly = poly.fit_transform(X)


In [12]:
lr.fit(X_poly, y)
lr.coef_ , lr.intercept_

(array([ 1.48066807e+01, -6.23797591e-04]), 11336.68413381256)

In [13]:
#  More Variables

In [14]:
X, y = dum_df[['lotsize', 'bedrooms']], dum_df['price']

In [15]:
poly = PolynomialFeatures(degree=3, include_bias=False).set_output(transform='pandas')
X_poly = poly.fit_transform(X)
X_poly

lotsize  bedrooms  ...  lotsize bedrooms^2  bedrooms^3
0     5850.0       3.0  ...             52650.0        27.0
1     4000.0       2.0  ...             16000.0         8.0
2     3060.0       3.0  ...             27540.0        27.0
3     6650.0       3.0  ...             59850.0        27.0
4     6360.0       2.0  ...             25440.0         8.0
..       ...       ...  ...                 ...         ...
541   4800.0       3.0  ...             43200.0        27.0
542   6000.0       3.0  ...             54000.0        27.0
543   6000.0       3.0  ...             54000.0        27.0
544   6000.0       3.0  ...             54000.0        27.0
545   6000.0       3.0  ...             54000.0        27.0

[546 rows x 9 columns]

In [17]:
X_poly.columns

Index(['lotsize', 'bedrooms', 'lotsize^2', 'lotsize bedrooms', 'bedrooms^2',
       'lotsize^3', 'lotsize^2 bedrooms', 'lotsize bedrooms^2', 'bedrooms^3'],
      dtype='object')

In [16]:
lr.fit(X_poly, y)
lr.coef_ , lr.intercept_

(array([ 6.06875477e+00,  2.94843461e+02, -8.68104755e-04,  4.29837110e+00,
         1.04609172e+03,  2.32561206e-08, -9.87352621e-05, -1.31151307e-01,
        -3.50918785e+02]),
 8308.237517503541)

In [18]:
#  with All variables

In [19]:
X, y = dum_df.drop('price', axis =1), dum_df['price']
poly = PolynomialFeatures(degree=2, include_bias=False).set_output(transform='pandas')
X_poly = poly.fit_transform(X)

X_train, X_test, y_train, y_test = train_test_split(X_poly ,y , test_size=0.3, random_state=25)

lr = LinearRegression()
lr.fit(X_train, y_train)
y_pred = lr.predict(X_test)

r2_score(y_test, y_pred)


0.524015742469764

In [20]:
X_train.shape

(382, 77)

In [21]:
poly = PolynomialFeatures(degree=3, include_bias=False).set_output(transform='pandas')
X_poly = poly.fit_transform(X)

X_train, X_test, y_train, y_test = train_test_split(X_poly ,y , test_size=0.3, random_state=25)

lr = LinearRegression()
lr.fit(X_train, y_train)
y_pred = lr.predict(X_test)

r2_score(y_test, y_pred)


-0.5753642031440864

In [22]:
X, y = dum_df.drop('price', axis =1), dum_df['price']
poly = PolynomialFeatures(degree=2, include_bias=False).set_output(transform='pandas')
X_poly = poly.fit_transform(X)

X_train, X_test, y_train, y_test = train_test_split(X_poly ,y , test_size=0.3, random_state=25)


              

In [23]:
alphas = [0.001, 0.01, 0.1, 0.5, 1,2]
scores = []
for i in alphas:
    ridge = Ridge(alpha=i)
    ridge.fit(X_train, y_train)
    y_pred = ridge.predict(X_test)
    scores.append([i, r2_score(y_test, y_pred)])

df_scores = pd.DataFrame(scores, columns=['alpha', 'score'])
df_scores.sort_values('score', ascending=False).head()

/home/sarthakredasani/.local/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:215: LinAlgWarning: Ill-conditioned matrix (rcond=2.79691e-21): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/home/sarthakredasani/.local/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:215: LinAlgWarning: Ill-conditioned matrix (rcond=2.79691e-20): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/home/sarthakredasani/.local/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:215: LinAlgWarning: Ill-conditioned matrix (rcond=2.79691e-19): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/home/sarthakredasani/.local/lib/python3.11/site-packages/sklearn/linear_model/_ridge.py:215: LinAlgWarning: Ill-conditioned matrix (rcond=1.39846e-18): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
/home/sarthakred

alpha     score
5   2.00  0.627815
4   1.00  0.616622
3   0.50  0.604012
2   0.10  0.570190
1   0.01  0.532664

In [24]:
alphas = [0.001, 0.01, 0.1, 0.5, 1,2]
scores = []
for i in alphas:
    lasso = Lasso(alpha=i)
    lasso.fit(X_train, y_train)
    y_pred = lasso.predict(X_test)
    scores.append([i, r2_score(y_test, y_pred)])

df_scores = pd.DataFrame(scores, columns=['alpha', 'score'])
df_scores.sort_values('score', ascending=False).head()

/home/sarthakredasani/.local/lib/python3.11/site-packages/sklearn/linear_model/_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.866e+10, tolerance: 2.625e+07
  model = cd_fast.enet_coordinate_descent(
/home/sarthakredasani/.local/lib/python3.11/site-packages/sklearn/linear_model/_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.866e+10, tolerance: 2.625e+07
  model = cd_fast.enet_coordinate_descent(
/home/sarthakredasani/.local/lib/python3.11/site-packages/sklearn/linear_model/_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing reg

alpha     score
5   2.00  0.546992
4   1.00  0.536693
3   0.50  0.530603
2   0.10  0.525369
1   0.01  0.524156

In [25]:
alphas = [0.001, 0.01, 0.1, 0.5, 1,2]
ratios = [0.01, 0.25, 0.5, 0.75, 0.9]
scores = []
for i in alphas:
    for j in ratios:
        el = ElasticNet(alpha=i, l1_ratio=j)
        el.fit(X_train, y_train)
        y_pred = el.predict(X_test)
        scores.append([i, j ,  r2_score(y_test, y_pred)])

    

df_scores = pd.DataFrame(scores, columns=['alpha','ratio' , 'score'])
df_scores.sort_values('score', ascending=False).head()

/home/sarthakredasani/.local/lib/python3.11/site-packages/sklearn/linear_model/_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.977e+10, tolerance: 2.625e+07
  model = cd_fast.enet_coordinate_descent(
/home/sarthakredasani/.local/lib/python3.11/site-packages/sklearn/linear_model/_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.957e+10, tolerance: 2.625e+07
  model = cd_fast.enet_coordinate_descent(
/home/sarthakredasani/.local/lib/python3.11/site-packages/sklearn/linear_model/_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing reg

alpha  ratio     score
16    0.5   0.25  0.651853
23    1.0   0.75  0.651759
17    0.5   0.50  0.651749
15    0.5   0.01  0.651660
28    2.0   0.75  0.651653